name: 'Pull request labeler'

# ** What it does? **
#    - Auto labels PRs if certain files are changed.
# ** Why we have it? **
#    - To easily determine what changes have happened.
# ** Who does it impact? **
#    - All developers.

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  label_pull_request:
    name: 'Add labels to pull request'
    runs-on: ubuntu-latest
    env:
      DEVELOPMENT_URL: 'test url'
    steps:
      - name: 'Label'
        id: 'labeling'
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Assign users for devops labels'
        # if: contains(github.event.pull_request.labels, 'devops')
        run: echo ${{ github.event.pull_request.labels }}
        # uses: murs313/request-review@v1.0
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}
        #   reviewers: 'dinostancic'



