name: 'Pull request labeler'

# ** What it does? **
#    - Auto labels PRs if certain files are changed.
# ** Why we have it? **
#    - To easily determine what changes have happened.
# ** Who does it impact? **
#    - All developers.

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  label_pull_request:
    name: 'Add labels to pull request'
    runs-on: ubuntu-latest
    env:
      DEVELOPMENT_URL: 'test url'
    steps:
      - name: 'Label'
        id: 'labeling'
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Notify about successful deployment'
        env:
          JSON: fromJSON(steps.labeling)
        run: echo "${{ env.JSON }}"
        # uses: JoseThen/comment-pr@v1.1.1
        # with:
        #   comment: 'This PR is the best ${{ env.DEVELOPMENT_URL }}'
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    