name: 'Pull request labeler'

# ** What it does? **
#    - Auto labels PRs if certain files are changed.
# ** Why we have it? **
#    - To easily determine what changes have happened.
# ** Who does it impact? **
#    - All developers.

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  label_pull_request:
    name: 'Add labels to pull request'
    runs-on: ubuntu-latest
    env:
      DEVELOPMENT_URL: 'test url'
    steps:
      - name: 'Label'
        id: 'labeling'
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 'Assign users based on the labels in the assignee4label.yml'
        uses: kyanagimoto/assignee4label@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: '.github/assignee4label.yml'        