name: 'Pull request labeler'

# ** What it does? **
#    - Auto labels PRs if certain files are changed.
# ** Why we have it? **
#    - To easily determine what changes have happened.
# ** Who does it impact? **
#    - All developers.

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  label_pull_request:
    name: 'Add labels to pull request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  
  notify:
    env:
      PRODUCTION_URL: "test" # Add url of firebase hosting project
    if: github.event.workflow.action.completed
    runs-on: ubuntu-latest
    steps: 
      - name: 'Notify about successful deployment'
        uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Deploy to firebase hosting was successful. You can check your application here: ${{ env.PRODUCTION_URL }}'

    