name: 'Check if PR has description'

on: 
  pull_request:
    types: 
      - opened
      - reopened
      - edited

jobs: 
  no_description_pr:
    name: 'Check if PR has description'
    runs-on: ubuntu-latest
    steps: 
      - if: ${{ github.event.pull_request.body == null }}
        name: Close PR if there is no description
        uses: peter-evans/close-pull@v2
        with:
          comment: "Please provide a description of a pull request."

