name: 'Check if PR has at least one reviewer'

# ** What it does? **
#    - Checks if PR has at least one reviewer.
# ** Why we have it? **
#    - So our PR's don't get merged unsupervised.
# ** Who does it impact? **
#    - All developers.



on: 
  pull_request:
    types: 
      - opened
      - reopened
      - edited
      - assigned

jobs: 
  pr_reviewer_check:
    name: 'Check if PR has at least one reviewer'
    if: github.event.pull_request.requested_reviewers != '[]'  
    runs-on: ubuntu-latest
    steps: 
      - name: Set PR draft if there are no reviewers
        uses: voiceflow/daft-pr@latest