name: 'Check if PR has at least one reviewer'

# ** What it does? **
#    - Checks if PR has at least one reviewer.
# ** Why we have it? **
#    - So our PR's don't get merged unsupervised.
# ** Who does it impact? **
#    - All developers.


on: 
  pull_request:
    types: 
      - opened
      - reopened
      - edited
      - assigned

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs: 
  pr_reviewer_check:
    name: 'Check if PR has at least one reviewer'
    if: github.event.pull_request.requested_reviewers != '[]' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps: 
        - uses: voiceflow/draft-pr@latest
          with: 
            token: ${{ secrets.GITHUB_TOKEN }}