name: 'Check if issue has description'

on: 
  issues:
    types: 
      - opened
      - reopened
      - edited

jobs: 
  no_issue_description:
    name: 'Check if issue has description'
    runs-on: ubuntu-latest
    steps: 
      - if: ${{ github.event.issue.body == null }}
        name: Close Issue if there is no description
        uses: peter-evans/close-issue@v2
        with:
          comment: "Please provide a description of an issue."

