name: 'Generate changelog PROD'

# ** What it does? **
#    - Generate changelogs for each release.
# ** Why we have it? **
#    - To have the consistent CHANGELOG.md file in our repository.
# ** Who does it impact? **
#    - All contributors.

on:
  release:
    types: [published]

jobs:
  update:
    if: ${{ !contains(github.ref, '-rc') }}
    name: 'Generate changelog PROD'
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # updated CHANGELOG back to the repository.
      # https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

      - name: Create PR for Changelog
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'Update CHANGELOG - Release ${{ github.event.release.tag_name }}'
          body: 'Update Changelog.md'

      # Merge the PR if all checks pass
      - name: Merge PR
        # This ensures the step runs only if all previous steps were successful
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const { context, github } = require('@actions/github');
            const pull_request_number = context.payload.pull_request.number;
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_request_number,
              merge_method: 'rebase'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
