name: "Generate changelog"

# ** What it does? **
#    - Generate changelogs for each release.
# ** Why we have it? **
#    - To have the consistent CHANGELOG.md file in our repository.
# ** Who does it impact? **
#    - All contributors.

on:
  release:
    types: 
      - published

jobs:
  update:
    if: contains(github.event.release.tag_name, 'live')
    name: 'Generate changelog'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Fetch entire history of repository to ensure relase date can be
          # extracted from commit of the given tag.
          fetch-depth: 0
          # Checkout target branch of this release. Ensures that the CHANGELOG
          # is not out of date.
          ref: ${{ github.event.release.target_commitish }}

      - name: Check CHANGELOG.md existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "CHANGELOG.md"

      - name: Create CHANGELOG.md
        if: steps.check_files.outputs.files_exists == 'false'
        # Only runs if CHANGELOG.md doesn't exist
        uses: 1arp/create-a-file-action@0.2
        with:
          path: '.'
          file: 'CHANGELOG.md'
          content: |
            # Changelog
      

      - name: Extract release date from git tag
        id: release_date
        run: |
          echo "::set-output name=date::$(git log -1 --date=short --format=%ad '${{ github.event.release.tag_name }}')"

      - name: Extract release version from git tag
        id: release_version
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: echo "::set-output name=release_version::${RELEASE_TAG_NAME##*-}"

      - name: Remove titles from release notes
        id: removed_titles
        uses: ashley-taylor/regex-property-action@v1.3
        with:
          value: ${{ github.event.release.body }}
          regex: '\#{2}\s\b.*'
          replacement: ""

      - name: Remove trailing full changelog link from release notes
        id: clean_release_notes
        uses: ashley-taylor/regex-property-action@v1.3
        with:
          value: ${{ steps.removed_titles.outputs.value }}
          regex: '(.\*.*)'
          replacement: ""
      
      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          # Pass parsed release date, release notes and version to the Action.
          release-date: ${{ steps.release_date.outputs.date }}
          release-notes: ${{ steps.clean_release_notes.outputs.value }}
          latest-version: '[${{ steps.release_version.outputs.release_version }}]'
          compare-url-target-revision: ${{ github.event.release.target_commitish }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Push updated CHANGELOG to release target branch.
          create_branch: true
          branch: feature/changelog-change-${{ github.event.release.tag_name }}
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

      - name: Create PR for Changelog
        id: create_pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ github.token }}
          source_branch: "feature/changelog-change-${{ github.event.release.tag_name }}"
          destination_branch: "main"
          pr_title: "Update CHANGELOG - Release ${{ github.event.release.tag_name }}"
          pr_body: "Update Changelog.md"
        
      - name: Auto approve CHANGELOG PR
        if: steps.create_pr.outputs.pr_created == 'true'
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ github.token }}
          number: ${{ steps.create_pr.outputs.pr_number }}

      - name: Automerge CHANGELOG PR 
        if: steps.create_pr.outputs.pr_created == 'true'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ github.token }}
          pull-request-number: ${{ steps.create_pr.outputs.pr_number }}