name: Add Google Calendar Event on Release

on:
  release:
    types: [published]

jobs:
  add-event-to-google-calendar:
    name: Add Google Calendar Event
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add Google Calendar Event
        uses: stancic/create-google-calendar-event@v1.2.1
        with:
          service_account_client_email: ${{ secrets.SERVICE_ACCOUNT_CLIENT_EMAIL }}
          service_account_client_private_key: ${{ secrets.SERVICE_ACCOUNT_CLIENT_PRIVATE_KEY }}
          calendar_id: ${{ secrets.GOOGLE_CALENDAR_ID }}
          summary: ${{ github.event.release.name }}
          description: ${{ github.event.release.body }}
