on: 
  pull_request:
    types: 
      - opened
      - reopened

jobs: 
  pr_opened:
    runs-on: ubuntu-latest
    name: Close PR if there is no description
    steps: 
      - name: What PR contains
        run: echo ${{ github }}
        shell: bash

