name: 'Rename stale'

# ** What it does? **
#    - Check PRs and if they're stale, rename them.
# ** Why we have it? **
#    - To easily know which PR is marked as stale.
# ** Who does it impact? **
#    - All developers.

on: 
  schedule:
    - cron: '15 13 * * *' # Run each day at 16:00 UTC -> 18:00 CEST (Croatia)

  push:
  pull_request:
    types:
      - labeled
      - unlabeled
      - edited
      - reopened
      - review_requested
  label:
    types:
      - created
      - edited
      - deleted

permissions:
  pull-requests: write

jobs:
  add_stale_tag_to_title:
    name: 'Add stale tag to title if label has changed'
    if: contains(github.event.pull_request.labels.*.name, 'stale')
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch-regex: '[a-zA-Z\d-_.\\/]+'
          title-template: "[STALE] "

